//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAuth
    {
        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string LoginName { get; set; }
        public string PasswordHash { get; set; }
        public int AccessFailedCount { get; set; }
        public Nullable<System.DateTime> LoginLastTime { get; set; }
        public bool Locked { get; set; }
        public string ActiveCode { get; set; }
        public string ResetPassNumber { get; set; }
    }
}
