//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid Id { get; set; }
        public string Keyword { get; set; }
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string DiDong { get; set; }
        public string Avatar { get; set; }
        public string Groups { get; set; }
        public int GioiTinh { get; set; }
        public int TrangThaiCongViec { get; set; }
        public bool Developer { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> Priority { get; set; }
    }

    public partial class EmployeeBaseView
    {
        public Guid Id { get; set; }
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public int? OrganizationId { get; set; }
        public int? JobPositionId { get; set; }
        public string EmailCongTy { get; set; }
        public string OrganizationName { get; set; }
        public string JobPositionName { get; set; }
        public string JobTitleName { get; set; }
        public string Avatar { get; set; }
    }
}
