//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionValue
    {
        public int Id { get; set; }
        public string Keyword { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string MoRong1 { get; set; }
        public string MoRong2 { get; set; }
        public string MoRong3 { get; set; }
        public string MoRong4 { get; set; }
        public string MoRong5 { get; set; }
        public string Note { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public bool AllowChange { get; set; } 
    }
}
