//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;
namespace DBContext.AuthSharing.Entities
{
    using System;
    using System.Collections.Generic;

	public partial class LocalNation
	{
		public int Id { get; set; }
		public string Keyword { get; set; }
		public string Code { get; set; }
		public int Type { get; set; }
		public string Name { get; set; }
		public int Priority { get; set; }
		public string MaThue { get; set; }
	}
	 
    public partial class LocalCountry
	{
        public int Id { get; set; }
        public string Keyword { get; set; }
        public string MaTinh { get; set; }
        public string Name { get; set; }
        public decimal Lat { get; set; }
        public decimal Lng { get; set; }
        public int? Nation { get; set; }
        public Nullable<System.DateTime> Priority { get; set; }
        public string MapName { get; set; }
        public string MaThue { get; set; }
    }


	public partial class LocalDistrict
	{
		public int Id { get; set; }
		public string Code { get; set; }
		public string MaHuyen { get; set; }
		public string Keyword { get; set; }
		public string Name { get; set; }
		public int CountryId { get; set; }
		public decimal Lat { get; set; }
		public decimal Lng { get; set; }
		public Nullable<System.DateTime> Priority { get; set; }
		public string MapName { get; set; }
		public string MaThue { get; set; }
	}

	public partial class LocalWard
	{
		public int Id { get; set; }
		public string Keyword { get; set; }
		public string Code { get; set; }
		public string MaPhuong { get; set; }
		public string Name { get; set; }
		public int DistrictId { get; set; }
		public string MaThue { get; set; }
	}
}
