//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext.AuthSharing.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class LocalEmployee
    {
        public System.Guid Id { get; set; }
        public string Keyword { get; set; }
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public string EmailCongTy { get; set; }
        public string DiDong { get; set; }
        public string Avatar { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int Status { get; set; }
        public bool Locked { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public int? JobPositionId { get; set; }
        public int? OrganizationId { get; set; }
        public bool IsAdmin { get; set; }
    }
    public partial class LocalEmployeeAuthView
    {
        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string LoginName { get; set; }
        public string PasswordHash { get; set; } 
        public bool Locked { get; set; }
    }
    public partial class LocalEmployeeView
    {
        public System.Guid Id { get; set; }
        public string Keyword { get; set; }
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public string EmailCongTy { get; set; }
        public string DiDong { get; set; }
        public string Avatar { get; set; }
        public int TrangThaiCongViec { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int Status { get; set; }
        public bool Locked { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public int? JobPositionId { get; set; }
        public int? OrganizationId { get; set; }
        public int? JobTitleId { get; set; }
        public string OrganizationName { get; set; }
        public string JobPositionName { get; set; }
        public int? GroupId { get; set; }
        public bool IsAdmin { get; set; }
    }
    public partial class LocalEmployeeBaseView
    {
        public System.Guid Id { get; set; } 
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public string EmailCongTy { get; set; }
        public string Avatar { get; set; }
        public int? JobPositionId { get; set; }
        public int? OrganizationId { get; set; }
        public int? JobTitleId { get; set; }
        public string OrganizationName { get; set; }
        public string JobPositionName { get; set; }
        public string JobTitleName { get; set; }
    }
}
