//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext.AuthSharing.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class LocalOrganization
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Keyword { get; set; }
        public string Code { get; set; }
        public Guid? OwnerId { get; set; }
        public Guid? InOwnerId1 { get; set; }
        public Guid? InOwnerId2 { get; set; }
        public Guid? InOwnerId3 { get; set; }
        public Guid? InOwnerId4 { get; set; }
        public int Type { get; set; }
        public int KhuVuc { get; set; }
        public Nullable<double> Priority { get; set; }
        public bool Stopped { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public int Status { get; set; }
    }
}
