//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext.AuthSharing.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalEmpWorkLog
    {
        public Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> PerformBy { get; set; }
        public string ObjectType { get; set; }
        public string ObjectId { get; set; }
        public string Message { get; set; }
        public string IP { get; set; }
        public string UserAgent { get; set; }
        public string Note { get; set; }
    }
}
