//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext.AuthSharing.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalOrganizationListView
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ParentStr { get; set; }
        public string Name { get; set; }
        public string Keyword { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> NgayThanhLap { get; set; }
        public Nullable<int> DirectManager { get; set; }
        public string IndirectManagers { get; set; }
        public int Type { get; set; }
        public int OrgLevelId { get; set; }
        public Nullable<int> LoaiHinhDuAn { get; set; }
        public Nullable<double> Priority { get; set; }
        public bool Stopped { get; set; }
        public int Status { get; set; }
        public int TotalEmployee { get; set; }
        public bool PrivateCount { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
        public Nullable<int> KhuVuc { get; set; }
    }
}
